# Generated by roxytest: Do not edit by hand!

# File R/clean_model_dir.R: @testexamples

test_that("Function clean_model_dir() @ L14", {
  
  
  clean_model_dir()
  
  expect_message(clean_model_dir(), "Done")
})

