# Generated by roxytest: Do not edit by hand!

# File R/filter_ezcox.R: @testexamples

test_that("Function filter_ezcox() @ L24", {
  
  library(survival)
  lung$ph.ecog <- factor(lung$ph.ecog)
  zz <- ezcox(lung, covariates = c("sex", "age"), controls = "ph.ecog")
  zz
  filter_ezcox(zz)
  filter_ezcox(zz, c("0", "2"))
  filter_ezcox(zz, c("0", "2"), type = "contrast")
  t <- filter_ezcox(zz, c("0", "2"), type = "ref")
  t
  expect_s3_class(t, "ezcox")
})

