# Generated by roxytest: Do not edit by hand!

context("File R/forester.R: @testexamples")

test_that("Function forester() @ L60", {
  
  library(survival)
  
  t1 <- ezcox(lung, covariates = c(
    "age", "sex",
    "ph.karno", "pat.karno"
  ))
  p <- forester(t1, xlim = c(0, 1.5))
  p
  p2 <- forester(t1, xlim = c(0.5, 1.5))
  p2
  expect_s3_class(p, "ggplot")
  expect_s3_class(p2, "ggplot")
})

