# Generated by roxytest: Do not edit by hand!

# File R/get_models.R: @testexamples

test_that("Function get_models() @ L16", {
  
  library(survival)
  zz <- ezcox(lung, covariates = c("sex", "ph.ecog"), controls = "age", return_models = TRUE)
  mds <- get_models(zz)
  str(mds, max.level = 1)
  expect_s3_class(mds, "ezcox_models")
})

