# Generated by roxytest: Do not edit by hand!

context("File R/ezcox_parallel.R: @testexamples")

test_that("Function ezcox_parallel() @ L37", {
  
  library(survival)
  t <- ezcox_parallel(lung, covariates = c("sex", "ph.ecog"), controls = "age")
  t
  expect_s3_class(t, "ezcox")
})

