# Generated by roxytest: Do not edit by hand!

# File R/ezgrp.R: @testexamples

test_that("Function ezcox_group() @ L22", {
  
  library(survival)
  ezcox_group(lung, grp_var = "sex", covariate = "ph.ecog")
  ezcox_group(lung, grp_var = "sex", covariate = "ph.ecog", controls = "age")
  p <- ezcox_group(lung,
    grp_var = "sex", covariate = "ph.ecog",
    controls = "age", add_all = TRUE
  )
  expect_is(p, "list")
})

